name: Publicar Libro

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Versión del libro (ej. v1.0.0)'
        required: true
        default: ''

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Typst
        uses: typst-community/setup-typst@v4

      - name: Crear carpeta de salida
        run: mkdir -p build

      - name: Compilar libro
        run: typst compile --font-path src/fonts --format pdf src/main.typ build/libro-python-backend.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: libro-python-backend
          path: build/libro-python-backend.pdf
